version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  # Install dependencies and environment setup
  setup:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Set up environment
          command: |
            echo "GEMINI_API_KEY=${GEMINI_API_KEY}" > .env

  # Code Linting
  lint:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Run linter
          command: |
            pip install flake8
            flake8 .

  # Run tests
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            pip install pytest
            pytest

  # Deployment
  deploy:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Deploy to server
          command: |
            echo "Deploying application..."
            # Add your deployment commands here, e.g., SSH into a server and pull updates.

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
      - deploy:
          requires:
            - test
